arrowParens: avoid
bracketSpacing: true
embeddedLanguageFormatting: auto
endOfLine: lf
jsxSingleQuote: false
printWidth: 80
proseWrap: always
quoteProps: as-needed
semi: false
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
plugins:
  - prettier-plugin-tailwindcss
overrides:
  - files: '*.svg'
    options:
      parser: html
